2018-11-26 20:39:19,795 INFO: Microblog startup [in D:\flask_microblog\flask_microblog\app\__init__.py:51]
2018-11-26 20:41:06,985 ERROR: Exception on /edit_profile [GET] [in c:\program files\python3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\program files\python3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\program files\python3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\program files\python3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\program files\python3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\program files\python3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\program files\python3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\flask_microblog\flask_microblog\app\routes.py", line 98, in edit_profile
    form = EditProfileForm()
  File "c:\program files\python3\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2018-11-26 20:41:28,143 ERROR: Exception on /edit_profile [GET] [in c:\program files\python3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\program files\python3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\program files\python3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\program files\python3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\program files\python3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\program files\python3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\program files\python3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\flask_microblog\flask_microblog\app\routes.py", line 98, in edit_profile
    form = EditProfileForm()
  File "c:\program files\python3\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2018-11-26 20:41:45,107 ERROR: Exception on /edit_profile [GET] [in c:\program files\python3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\program files\python3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\program files\python3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\program files\python3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\program files\python3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\program files\python3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\program files\python3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\flask_microblog\flask_microblog\app\routes.py", line 98, in edit_profile
    form = EditProfileForm()
  File "c:\program files\python3\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2018-11-26 20:45:55,379 INFO: Microblog startup [in D:\flask_microblog\flask_microblog\app\__init__.py:51]
2018-11-26 20:46:08,738 ERROR: Exception on /edit_profile [GET] [in c:\program files\python3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\program files\python3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\program files\python3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\program files\python3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\program files\python3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\program files\python3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\program files\python3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files\python3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\flask_microblog\flask_microblog\app\routes.py", line 98, in edit_profile
    form = EditProfileForm()
  File "c:\program files\python3\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2018-11-26 21:14:22,405 INFO: Microblog startup [in D:\flask_microblog\flask_microblog\app\__init__.py:51]
2018-11-26 21:17:05,297 INFO: Microblog startup [in D:\flask_microblog\flask_microblog\app\__init__.py:51]
2018-11-26 21:17:55,161 INFO: Microblog startup [in D:\flask_microblog\flask_microblog\app\__init__.py:51]
2018-11-26 21:18:23,305 INFO: Microblog startup [in D:\flask_microblog\flask_microblog\app\__init__.py:51]
2018-11-26 21:18:41,743 INFO: Microblog startup [in D:\flask_microblog\flask_microblog\app\__init__.py:51]
2018-11-26 22:11:43,779 INFO: Microblog startup [in D:\flask_microblog\flask_microblog\app\__init__.py:51]
2018-11-26 22:38:31,604 INFO: Microblog startup [in D:\flask_microblog\flask_microblog\app\__init__.py:51]
2018-11-26 22:42:32,842 INFO: Microblog startup [in D:\flask_microblog\flask_microblog\app\__init__.py:51]
2018-11-27 04:55:00,751 INFO: Microblog startup [in D:\flask_microblog\flask_microblog\app\__init__.py:51]
2018-11-27 04:55:20,119 INFO: Microblog startup [in D:\flask_microblog\flask_microblog\app\__init__.py:51]
2018-11-27 04:58:27,305 INFO: Microblog startup [in D:\flask_microblog\flask_microblog\app\__init__.py:51]
2018-11-27 05:00:57,149 INFO: Microblog startup [in D:\flask_microblog\flask_microblog\app\__init__.py:51]
2018-11-27 05:01:33,846 INFO: Microblog startup [in D:\flask_microblog\flask_microblog\app\__init__.py:51]
2018-11-27 05:01:57,688 INFO: Microblog startup [in D:\flask_microblog\flask_microblog\app\__init__.py:51]
2018-11-27 05:02:34,446 INFO: Microblog startup [in D:\flask_microblog\flask_microblog\app\__init__.py:51]
